package es.upm.etsisi.poo.app3.data.model.shop.ticket;

import es.upm.etsisi.poo.app3.data.model.exceptions.InvalidAttributeException;
import es.upm.etsisi.poo.app3.data.model.shop.products.*;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;

/**
 * The {@code TicketItem} class represents a single line item inside a {@link Ticket}.
 * <p>
 * A ticket item binds a {@link Purchasable} element (product or service) to a quantity
 * and keeps track of the discount applied to that purchasable. It also supports
 * additional customization data (e.g., texts for {@link CustomProduct}) that must be
 * persisted along with the item.
 * </p>
 *
 * <p>
 * This entity is persisted independently and referenced by {@link Ticket} through a
 * one-to-many relationship. Each item has an internal technical identifier used for
 * database ordering and traceability.
 * </p>
 *
 * <p><b>Example usage:</b></p>
 * <pre>{@code
 * TicketItem item = new TicketItem(new BasicProduct(product), 2);
 * double total = item.getTotalPrice();
 * double discount = item.getDiscount();
 * }</pre>
 *
 * @author Jiling
 * @version 3.0
 * @see Ticket
 * @see Purchasable
 * @see Product
 * @see ServiceProduct
 */
@Entity
@Table(name = "ticket_items")
public class TicketItem implements Comparable<TicketItem> {

    /**
     * Technical identifier for persistence purposes.
     * <p>
     * This identifier is generated by the database and is mainly used to preserve
     * ordering and provide a stable reference for the entity.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long internalId;

    /**
     * Purchasable element associated with this ticket item (product or service).
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "purchasable_id")
    private Purchasable purchasable;

    /**
     * Quantity of units for the purchasable element.
     */
    @Column(name = "quantity")
    private int quantity;

    /**
     * Discount rate applied to this ticket item (as a fraction, e.g., 0.10 for 10%).
     */
    private double discountApplied;

    /**
     * Custom text fragments associated with the item, mainly used for {@link CustomProduct}.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
            name = "ticket_item_customTexts",
            joinColumns = @JoinColumn(name = "ticket_item_id")
    )
    private List<String> customTexts;

    /**
     * Protected no-argument constructor required by JPA.
     */
    protected TicketItem() {}

    /**
     * Creates a ticket item for a generic purchasable element.
     * <p>
     * The discount is initialized to {@code 0.0}. This constructor is typically used
     * for services or purchasables where the discount is computed externally.
     * </p>
     *
     * @param purchasable the purchasable element
     * @param quantity    the quantity to assign
     * @throws InvalidAttributeException if quantity is not positive
     */
    public TicketItem(Purchasable purchasable, Integer quantity) {
        if (quantity <= 0) {
            throw new InvalidAttributeException("Quantity must be positive");
        }
        this.purchasable = purchasable;
        this.quantity = quantity;
        this.discountApplied = 0.0;
        this.customTexts = new ArrayList<>();
    }

    /**
     * Creates a ticket item for a basic product.
     * <p>
     * The discount rate is initialized using the product category discount.
     * </p>
     *
     * @param purchasable the basic product
     * @param quantity    the quantity to assign
     * @throws InvalidAttributeException if quantity is not positive
     */
    public TicketItem(BasicProduct purchasable, Integer quantity) {
        if (quantity <= 0) {
            throw new InvalidAttributeException("Quantity must be positive");
        }
        this.purchasable = purchasable;
        this.quantity = quantity;
        this.discountApplied = purchasable.getCategory().getDiscount();
        this.customTexts = new ArrayList<>();
    }

    /**
     * Creates a ticket item for a custom product, storing its associated custom texts.
     * <p>
     * The discount rate is initialized using the product category discount.
     * </p>
     *
     * @param purchasable  the custom product
     * @param quantity     the quantity to assign
     * @param customTexts  the custom texts associated with the product
     * @throws InvalidAttributeException if quantity is not positive
     */
    public TicketItem(CustomProduct purchasable, Integer quantity, List<String> customTexts) {
        if (quantity <= 0) {
            throw new InvalidAttributeException("Quantity must be positive");
        }
        this.purchasable = purchasable;
        this.quantity = quantity;
        this.discountApplied = purchasable.getCategory().getDiscount();
        this.customTexts = customTexts;
    }

    /**
     * Computes the total price for this item (unit price multiplied by quantity).
     *
     * @return the total price for this item
     */
    public Double getTotalPrice() {
        return this.purchasable.getUnitPrice(this) * this.quantity;
    }

    /**
     * Computes the discount amount applied to this item.
     *
     * @return the discount amount for this item
     */
    public Double getDiscount() {
        return this.discountApplied * this.getTotalPrice();
    }

    /**
     * Returns the purchasable element associated with this item.
     *
     * @return the purchasable element
     */
    public Purchasable<?> getPurchasable() {
        return this.purchasable;
    }

    /**
     * Returns the quantity of this item.
     *
     * @return the quantity
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Sets the quantity of this item.
     *
     * @param quantity the new quantity
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Returns the custom texts associated with this item.
     *
     * @return the list of custom texts
     */
    public List<String> getCustomTexts() {
        return this.customTexts;
    }

    /**
     * Sets the custom texts associated with this item.
     *
     * @param customTexts the list of custom texts
     */
    public void setCustomTexts(List<String> customTexts) {
        this.customTexts = customTexts;
    }

    /**
     * Returns the number of custom texts associated with this item.
     *
     * @return the number of custom texts
     */
    public int getCustomTextsSize() {
        return this.customTexts.size();
    }

    /**
     * Returns a string representation of the item.
     * <p>
     * This representation delegates to the associated purchasable element.
     * </p>
     *
     * @return a textual representation of the item
     */
    @Override
    public String toString() {
        return this.purchasable.toString();
    }

    /**
     * Compares this ticket item with another ticket item for ordering purposes.
     * <p>
     * Items are ordered by type first (products before services). When both items
     * are products, they are ordered lexicographically by product name. Otherwise,
     * ordering falls back to the purchasable identifier.
     * </p>
     *
     * @param other the other ticket item
     * @return a negative value, zero, or a positive value as this item is less than,
     *         equal to, or greater than the specified item
     */
    @Override
    public int compareTo(TicketItem other) {
        boolean thisIsProduct = this.purchasable instanceof Product;
        boolean otherIsProduct = other.purchasable instanceof Product;

        if (thisIsProduct && !otherIsProduct) return -1;
        if (!thisIsProduct && otherIsProduct) return 1;

        if (thisIsProduct) {
            String thisName = ((Product) this.purchasable).getName();
            String otherName = ((Product) other.purchasable).getName();
            return thisName.compareTo(otherName);
        }

        return this.purchasable.getId().toString()
                .compareTo(other.purchasable.getId().toString());
    }

    /**
     * Returns the discount rate applied to this item.
     *
     * @return the discount rate
     */
    public double getDiscountApplied() {
        return discountApplied;
    }

    /**
     * Sets the discount rate applied to this item.
     *
     * @param discountApplied the new discount rate
     */
    public void setDiscountApplied(double discountApplied) {
        this.discountApplied = discountApplied;
    }
}